[package]
name = "queuing_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.3.1" }
actix-cors = { version = "0.6.4" }
dotenvy = "0.15.7"
diesel = { version = "2.1.0", features = [
    "mysql",
    "mysql_backend",
    "chrono",
    "serde_json",
] }
randomforest = "0.1.6"
serde = { version = "1.0.163", features = ["derive"] }
chrono = { version = "0.4.26", features = ["serde"] }
simple-log = { version = "1.6.0" }
tokio = { version = "1.28.2", features = ["full"] }
async-std = "1.12.0"
futures = "0.3.28"
env_logger = "0.10.0"
log = "0.4.18"
